### ISSUE TITLE
loop時のエラーについて

### ISSUE THREAD

**Issue by mmochizuki** [kumitatepazuru/cszp#5]
/opt/cszp/config.confを削除して実行してみましたが、下記のエラーが出てしまいました。
---------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/cszp/main.py", line 139, in <module>
    main()
  File "/opt/cszp/main.py", line 107, in main
    r = cszp_menu.menu_en()
  File "/opt/cszp/cszp_menu.py", line 167, in menu_en
    cszp_soccer.setting_en_loop()
  File "/opt/cszp/cszp_soccer.py", line 951, in setting_en_loop
    loop(cmd, loops)
  File "/opt/cszp/cszp_soccer.py", line 169, in loop
    temp = open(df.split("'")[9]+"/"+file, "a")
IndexError: list index out of range
  0%|
---------------------------------------------------------------------
ちなみに、CSZPを実行すると、削除した/opt/cszp/config.confがもう一度作成されました。
ファイルの内容は下記の通りです。
---------------------------------------------------------------------------------------------------------------
soccerwindow2start,on,automake,off,rcglog output,on,rcllog output,on,logfile output,/opt/cszp
--------------------------------------------------------------------------------

**Comment by kumitatepazuru** [comment]
これはバグです。僕も少し前に見つけて修正しているのでアップデートをお待ち下さい。
commit次第お伝えします。

**Comment by kumitatepazuru** [comment]
修正しました。確認してください。
